// Structured, downloadable incident report generated automatically after SOS.
export type IncidentReport = {
  id: string;
  created_at: string;
  submitted_at: string | null;
  category: string;
  description: string | null;
  latitude: number | null;
  longitude: number | null;
  accuracy_m: number | null;
  address: string | null;
  device_info: DeviceInfo | null;
  trigger_method: string | null;
  contacts_notified: Array<{ name: string; phone: string; method: string }>;
  recording_status: string;
  recording_path: string | null;
  network_status: string | null;
  notes: string | null;
  status: string;
};

export type DeviceInfo = {
  platform: string;
  userAgent: string;
  language: string;
  screen: string;
  standalone: boolean;
  timezone: string;
};

export function collectDeviceInfo(): DeviceInfo {
  const nav = navigator as Navigator & { userAgentData?: { platform?: string } };
  return {
    platform: nav.userAgentData?.platform || navigator.platform || "unknown",
    userAgent: navigator.userAgent,
    language: navigator.language,
    screen: typeof window !== "undefined" ? `${window.screen.width}x${window.screen.height} @${window.devicePixelRatio}x` : "unknown",
    standalone: typeof window !== "undefined" && window.matchMedia("(display-mode: standalone)").matches,
    timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
  };
}

export function networkStatus(): string {
  const nav = navigator as Navigator & { connection?: { effectiveType?: string; downlink?: number } };
  if (!navigator.onLine) return "Offline";
  const c = nav.connection;
  return c?.effectiveType ? `Online (${c.effectiveType}${c.downlink ? `, ~${c.downlink} Mbps` : ""})` : "Online";
}

const RECORDING_LABEL: Record<string, string> = {
  none: "Not recorded",
  unsupported: "Not supported on this device/browser",
  denied: "Microphone permission denied",
  recording: "Recording in progress",
  queued: "Recorded — stored securely on this device, waiting for internet",
  uploaded: "Recorded — encrypted and uploaded securely",
  failed: "Recording failed",
};

export function recordingLabel(status: string | null | undefined) {
  return RECORDING_LABEL[status ?? "none"] ?? (status ?? "Unknown");
}

export function formatReport(r: IncidentReport): string {
  const d = new Date(r.submitted_at ?? r.created_at);
  const loc = r.latitude != null && r.longitude != null
    ? `${r.latitude.toFixed(6)}, ${r.longitude.toFixed(6)}${r.accuracy_m ? ` (±${Math.round(r.accuracy_m)} m)` : ""}`
    : "Not available";
  const maps = r.latitude != null && r.longitude != null
    ? `https://www.google.com/maps?q=${r.latitude},${r.longitude}`
    : "Not available";
  const contacts = r.contacts_notified?.length
    ? r.contacts_notified.map((c, i) => `   ${i + 1}. ${c.name} — ${c.phone} (${c.method})`).join("\n")
    : "   None";
  const dev = r.device_info;

  return [
    "ABHAYA — AUTOMATIC INCIDENT REPORT",
    "===================================",
    `Report ID       : ${r.id}`,
    `Date            : ${d.toLocaleDateString()}`,
    `Time            : ${d.toLocaleTimeString()}`,
    `Category        : ${r.category}`,
    `Status          : ${r.status}`,
    "",
    "LOCATION",
    `GPS Coordinates : ${loc}`,
    `Map Link        : ${maps}`,
    `Address         : ${r.address ?? "Not available"}`,
    "",
    "EMERGENCY DETAILS",
    `Trigger Method  : ${r.trigger_method ?? "Manual SOS"}`,
    `Network Status  : ${r.network_status ?? "Unknown"}`,
    `Recording       : ${recordingLabel(r.recording_status)}`,
    "",
    "CONTACTS NOTIFIED",
    contacts,
    "",
    "DEVICE INFORMATION",
    `Platform        : ${dev?.platform ?? "Unknown"}`,
    `Screen          : ${dev?.screen ?? "Unknown"}`,
    `Timezone        : ${dev?.timezone ?? "Unknown"}`,
    `Installed (PWA) : ${dev?.standalone ? "Yes" : "No"}`,
    `Browser         : ${dev?.userAgent ?? "Unknown"}`,
    "",
    "NOTES",
    r.notes?.trim() ? r.notes : "   —",
    "",
    "Generated by Abhaya. This report is a factual record of an SOS event",
    "created on the user's device. It is not a police complaint (FIR).",
  ].join("\n");
}

export function downloadReport(r: IncidentReport) {
  const blob = new Blob([formatReport(r)], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `abhaya-incident-${new Date(r.submitted_at ?? r.created_at).toISOString().slice(0, 19).replace(/[:T]/g, "-")}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}
