/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedZeroFirRouteImport } from './routes/_authenticated/zero-fir'
import { Route as AuthenticatedSosRouteImport } from './routes/_authenticated/sos'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSchemesRouteImport } from './routes/_authenticated/schemes'
import { Route as AuthenticatedRightsRouteImport } from './routes/_authenticated/rights'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedLiveLocationRouteImport } from './routes/_authenticated/live-location'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated/learn'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHelplineRouteImport } from './routes/_authenticated/helpline'
import { Route as AuthenticatedHarassmentRouteImport } from './routes/_authenticated/harassment'
import { Route as AuthenticatedFollowingMeRouteImport } from './routes/_authenticated/following-me'
import { Route as AuthenticatedFaqRouteImport } from './routes/_authenticated/faq'
import { Route as AuthenticatedDomesticViolenceRouteImport } from './routes/_authenticated/domestic-violence'
import { Route as AuthenticatedCyberSafetyRouteImport } from './routes/_authenticated/cyber-safety'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedZeroFirRoute = AuthenticatedZeroFirRouteImport.update({
  id: '/zero-fir',
  path: '/zero-fir',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSosRoute = AuthenticatedSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchemesRoute = AuthenticatedSchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRightsRoute = AuthenticatedRightsRouteImport.update({
  id: '/rights',
  path: '/rights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveLocationRoute =
  AuthenticatedLiveLocationRouteImport.update({
    id: '/live-location',
    path: '/live-location',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelplineRoute = AuthenticatedHelplineRouteImport.update({
  id: '/helpline',
  path: '/helpline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHarassmentRoute = AuthenticatedHarassmentRouteImport.update({
  id: '/harassment',
  path: '/harassment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowingMeRoute =
  AuthenticatedFollowingMeRouteImport.update({
    id: '/following-me',
    path: '/following-me',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFaqRoute = AuthenticatedFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDomesticViolenceRoute =
  AuthenticatedDomesticViolenceRouteImport.update({
    id: '/domestic-violence',
    path: '/domestic-violence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCyberSafetyRoute =
  AuthenticatedCyberSafetyRouteImport.update({
    id: '/cyber-safety',
    path: '/cyber-safety',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/language': typeof LanguageRoute
  '/onboarding': typeof OnboardingRoute
  '/about': typeof AuthenticatedAboutRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/cyber-safety': typeof AuthenticatedCyberSafetyRoute
  '/domestic-violence': typeof AuthenticatedDomesticViolenceRoute
  '/faq': typeof AuthenticatedFaqRoute
  '/following-me': typeof AuthenticatedFollowingMeRoute
  '/harassment': typeof AuthenticatedHarassmentRoute
  '/helpline': typeof AuthenticatedHelplineRoute
  '/home': typeof AuthenticatedHomeRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/live-location': typeof AuthenticatedLiveLocationRoute
  '/map': typeof AuthenticatedMapRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/report': typeof AuthenticatedReportRoute
  '/rights': typeof AuthenticatedRightsRoute
  '/schemes': typeof AuthenticatedSchemesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sos': typeof AuthenticatedSosRoute
  '/zero-fir': typeof AuthenticatedZeroFirRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/language': typeof LanguageRoute
  '/onboarding': typeof OnboardingRoute
  '/about': typeof AuthenticatedAboutRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/cyber-safety': typeof AuthenticatedCyberSafetyRoute
  '/domestic-violence': typeof AuthenticatedDomesticViolenceRoute
  '/faq': typeof AuthenticatedFaqRoute
  '/following-me': typeof AuthenticatedFollowingMeRoute
  '/harassment': typeof AuthenticatedHarassmentRoute
  '/helpline': typeof AuthenticatedHelplineRoute
  '/home': typeof AuthenticatedHomeRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/live-location': typeof AuthenticatedLiveLocationRoute
  '/map': typeof AuthenticatedMapRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/report': typeof AuthenticatedReportRoute
  '/rights': typeof AuthenticatedRightsRoute
  '/schemes': typeof AuthenticatedSchemesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sos': typeof AuthenticatedSosRoute
  '/zero-fir': typeof AuthenticatedZeroFirRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/language': typeof LanguageRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/cyber-safety': typeof AuthenticatedCyberSafetyRoute
  '/_authenticated/domestic-violence': typeof AuthenticatedDomesticViolenceRoute
  '/_authenticated/faq': typeof AuthenticatedFaqRoute
  '/_authenticated/following-me': typeof AuthenticatedFollowingMeRoute
  '/_authenticated/harassment': typeof AuthenticatedHarassmentRoute
  '/_authenticated/helpline': typeof AuthenticatedHelplineRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRoute
  '/_authenticated/live-location': typeof AuthenticatedLiveLocationRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/rights': typeof AuthenticatedRightsRoute
  '/_authenticated/schemes': typeof AuthenticatedSchemesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sos': typeof AuthenticatedSosRoute
  '/_authenticated/zero-fir': typeof AuthenticatedZeroFirRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/language'
    | '/onboarding'
    | '/about'
    | '/assistant'
    | '/contacts'
    | '/cyber-safety'
    | '/domestic-violence'
    | '/faq'
    | '/following-me'
    | '/harassment'
    | '/helpline'
    | '/home'
    | '/learn'
    | '/live-location'
    | '/map'
    | '/notifications'
    | '/profile'
    | '/report'
    | '/rights'
    | '/schemes'
    | '/settings'
    | '/sos'
    | '/zero-fir'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/language'
    | '/onboarding'
    | '/about'
    | '/assistant'
    | '/contacts'
    | '/cyber-safety'
    | '/domestic-violence'
    | '/faq'
    | '/following-me'
    | '/harassment'
    | '/helpline'
    | '/home'
    | '/learn'
    | '/live-location'
    | '/map'
    | '/notifications'
    | '/profile'
    | '/report'
    | '/rights'
    | '/schemes'
    | '/settings'
    | '/sos'
    | '/zero-fir'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/language'
    | '/onboarding'
    | '/_authenticated/about'
    | '/_authenticated/assistant'
    | '/_authenticated/contacts'
    | '/_authenticated/cyber-safety'
    | '/_authenticated/domestic-violence'
    | '/_authenticated/faq'
    | '/_authenticated/following-me'
    | '/_authenticated/harassment'
    | '/_authenticated/helpline'
    | '/_authenticated/home'
    | '/_authenticated/learn'
    | '/_authenticated/live-location'
    | '/_authenticated/map'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/report'
    | '/_authenticated/rights'
    | '/_authenticated/schemes'
    | '/_authenticated/settings'
    | '/_authenticated/sos'
    | '/_authenticated/zero-fir'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LanguageRoute: typeof LanguageRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/zero-fir': {
      id: '/_authenticated/zero-fir'
      path: '/zero-fir'
      fullPath: '/zero-fir'
      preLoaderRoute: typeof AuthenticatedZeroFirRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sos': {
      id: '/_authenticated/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof AuthenticatedSosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schemes': {
      id: '/_authenticated/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof AuthenticatedSchemesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rights': {
      id: '/_authenticated/rights'
      path: '/rights'
      fullPath: '/rights'
      preLoaderRoute: typeof AuthenticatedRightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-location': {
      id: '/_authenticated/live-location'
      path: '/live-location'
      fullPath: '/live-location'
      preLoaderRoute: typeof AuthenticatedLiveLocationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/helpline': {
      id: '/_authenticated/helpline'
      path: '/helpline'
      fullPath: '/helpline'
      preLoaderRoute: typeof AuthenticatedHelplineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/harassment': {
      id: '/_authenticated/harassment'
      path: '/harassment'
      fullPath: '/harassment'
      preLoaderRoute: typeof AuthenticatedHarassmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/following-me': {
      id: '/_authenticated/following-me'
      path: '/following-me'
      fullPath: '/following-me'
      preLoaderRoute: typeof AuthenticatedFollowingMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faq': {
      id: '/_authenticated/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof AuthenticatedFaqRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domestic-violence': {
      id: '/_authenticated/domestic-violence'
      path: '/domestic-violence'
      fullPath: '/domestic-violence'
      preLoaderRoute: typeof AuthenticatedDomesticViolenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cyber-safety': {
      id: '/_authenticated/cyber-safety'
      path: '/cyber-safety'
      fullPath: '/cyber-safety'
      preLoaderRoute: typeof AuthenticatedCyberSafetyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedCyberSafetyRoute: typeof AuthenticatedCyberSafetyRoute
  AuthenticatedDomesticViolenceRoute: typeof AuthenticatedDomesticViolenceRoute
  AuthenticatedFaqRoute: typeof AuthenticatedFaqRoute
  AuthenticatedFollowingMeRoute: typeof AuthenticatedFollowingMeRoute
  AuthenticatedHarassmentRoute: typeof AuthenticatedHarassmentRoute
  AuthenticatedHelplineRoute: typeof AuthenticatedHelplineRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRoute
  AuthenticatedLiveLocationRoute: typeof AuthenticatedLiveLocationRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedRightsRoute: typeof AuthenticatedRightsRoute
  AuthenticatedSchemesRoute: typeof AuthenticatedSchemesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSosRoute: typeof AuthenticatedSosRoute
  AuthenticatedZeroFirRoute: typeof AuthenticatedZeroFirRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedCyberSafetyRoute: AuthenticatedCyberSafetyRoute,
  AuthenticatedDomesticViolenceRoute: AuthenticatedDomesticViolenceRoute,
  AuthenticatedFaqRoute: AuthenticatedFaqRoute,
  AuthenticatedFollowingMeRoute: AuthenticatedFollowingMeRoute,
  AuthenticatedHarassmentRoute: AuthenticatedHarassmentRoute,
  AuthenticatedHelplineRoute: AuthenticatedHelplineRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRoute,
  AuthenticatedLiveLocationRoute: AuthenticatedLiveLocationRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedRightsRoute: AuthenticatedRightsRoute,
  AuthenticatedSchemesRoute: AuthenticatedSchemesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSosRoute: AuthenticatedSosRoute,
  AuthenticatedZeroFirRoute: AuthenticatedZeroFirRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LanguageRoute: LanguageRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
